### ISSUE TITLE
Pretty weird behavior sometimes

### ISSUE THREAD

**Issue by dieggsy** [ecraven/no-emoji#1]
For example:

![2018-01-20_16 35 19](https://user-images.githubusercontent.com/9020453/35188270-616c62a6-fe00-11e7-9b3d-1f1377d2ca0c.png)

I can't consistently reproduce this, and sometimes it is fixed by turning the mode off and back on. The emoji in that case (both times) was `:pile-of-poo:`.

**Comment by ecraven** [comment]
Thank you, can reproduce, just need to figure out what the problem is :-/

**Comment by ecraven** [comment]
So, the reason for this is that `get-unicode-property-internal` returns total garbage until `insert-char` is called at least once interactively. Trying to find out how to fix this.

**Comment by ecraven** [comment]
Thanks to Eli for pointing out to me that I was using an internal function instead of the proper `get-char-code-property'.
